### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by jonjon0815** [thewhobox/Kaenx#10]
Hello, is this project still being developed? 
Why can't I download it from the store? 
Where can I find the required Kaenx.Konnect project?

**Comment by thewhobox** [comment]
Hello,
this project is not under development yet.
I removed it from the store, because i wont support the old version anymore.
There will be a complete recode in the future. For now i will concentrate on the Kaenx-Creator and the integrated viewer.

The Kaenx-Konnect moved to another Organisation: https://github.com/OpenKNX/Kaenx-Konnect
